name: Build Terminal

on:
  workflow_dispatch:
  #push:
  #  branches:
  #    - main  # プッシュされたブランチがmainの場合のみ実行するように設定します

jobs:
  build:
    runs-on: ubuntu-latest  # 実行環境をUbuntuに設定します

    steps:
    - name: Checkout Repository  # リポジトリをチェックアウトします
      uses: actions/checkout@v2
      with:
     #     repository: xtermjs/xterm.js
          #ref: ${{ inputs.branch }}
          path: ./tarminal

    - name: Install Dependencies  # 必要な依存関係をインストールします（例えば、npm）
      run: npm install @xterm/xterm --legacy-peer-deps
      working-directory: ./tarminal

    #- name: Build Terminal  # ターミナルをビルドします
    #  run: npm run build  # このコマンドはTTY.jsを使ったターミナルのビルドを行うものとします
    #  working-directory: ./tarminal

    #- name: Upload Terminal  # ビルドされたターミナルファイルをアップロードします
    #  uses: actions/upload-artifact@v2
    #  with:
    #    name: terminal  # アーティファクトの名前を指定します
    #    path: ./tarminal  # ターミナルのビルドが出力されたパスを指定します

    - name: Deploy to gh-pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./tarminal
        destination_dir: ./
        keep_files: false

